name: PR Size

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    pull-request: write

jobs:
    calculate-size:
        runs-on: ubunutu-latest

        steps:
            - name: Checkout repository
            uses: actions/checkout@v4

            - name: Calculate PR size
            uses: actions/github-script@v7
            with:
                script: |
                const fs = require("fs");

                const owner = context.repo.owner;
                const repo = context.repo.repo;
                const pull_number = context.payload.pull_request.number;

                const labels = JSON.parse(
                  fs.readFileSync(".github/config/labels.json", "utf8"")
                );

                const sizeLabels = labels
                  .filter(label => label.name.startsWith("size/"))
                  .sort((a, b) => {
                    if (a.max === null) return 1;
                    if (b.max === null) return -1;

                    return a.max - b.max;
                  });

                const pullRequest = await github.rest.pulls.get({
                  owner,
                  repo,
                  pull_number
                });

                const additions = pullRequest.data.additions;
                const deletions = pullRequest.data.deletions;
                const changedLines = additions + deletions;

                const sizeLabel = sizeLabels.find(
                 label =>
                  label.max === null ||
                  changedLines <= label.max
                );

                if (!sizeLabel) {
                  core.setFailed("Could not determine PR size.");
                  return;
                }

                
                
                