name: Setup Labels

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs: 
  setup-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Create or update labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              { name: "build", color: "8b5cf6", description "build system or dependency changes" },
            ]